import type { Challenge, LeaderboardEntry, PassportItem } from "./types";

export const BRAND = {
  name: "SOLUTION HUNT",
  tagline: "SOLVE REAL PROBLEMS. BUILD REAL SOLUTIONS.",
  shortTagline: "REAL PROBLEMS. REAL TEAMS. REAL SOLUTIONS.",
};

export const publicNav = [
  { label: "Home", href: "/" },
  { label: "About", href: "/#about" },
  { label: "Challenges", href: "/challenges" },
  { label: "Schedule", href: "/#schedule" },
  { label: "Leaderboard", href: "/#leaderboard" },
  { label: "Teams", href: "/#teams" },
  { label: "Sponsors", href: "/#sponsors" },
  { label: "FAQ", href: "/#faq" },
];

export const passportStages: PassportItem[] = [
  { label: "Registration", shortLabel: "REG", complete: true },
  { label: "Orientation", shortLabel: "ORI", complete: true },
  { label: "Problem discovery", shortLabel: "DISC", complete: false },
  { label: "Mentor", shortLabel: "MENT", complete: false },
  { label: "Workshop", shortLabel: "WORK", complete: false },
  { label: "Judge", shortLabel: "JUDGE", complete: false },
  { label: "Demo", shortLabel: "DEMO", complete: false },
  { label: "Finale", shortLabel: "FINAL", complete: false },
];

export const challenges: Challenge[] = [
  {
    id: "SH-01",
    owner: "Campus Security Lab",
    title: "AI-Powered Cyber Threat Detection",
    category: "Cybersecurity",
    difficulty: "Advanced",
    points: 100,
    description: "Detect suspicious network activity before it becomes a real incident.",
    problem: "Modern organizations generate large volumes of network traffic every second. Manual detection is slow and inconsistent. Build an intelligent system that analyzes activity and identifies potential threats.",
    whyItMatters: "Earlier, clearer signals give security teams more time to respond and reduce the cost of a breach.",
    objective: ["Detect suspicious network behaviour", "Classify potential cyber threats", "Provide useful security alerts", "Present results through a clear dashboard"],
    requirements: ["Use AI, machine learning or intelligent rule-based detection", "Process network or security-related data", "Display meaningful threat information", "Focus on usability and real-world applicability"],
    deliverables: ["Working prototype", "Source code", "Project documentation", "Demo or presentation"],
    tags: ["AI", "ML", "Security"],
  },
  {
    id: "SH-02",
    owner: "AM Reddy Campus",
    title: "Smart Campus Security",
    category: "IoT",
    difficulty: "Intermediate",
    points: 80,
    description: "Create a smarter way to monitor and protect campus infrastructure.",
    problem: "Campuses contain classrooms, laboratories, hostels and shared facilities. Design a system that improves monitoring and quickly identifies unusual events.",
    whyItMatters: "A safer campus lets students and staff focus on learning, making and community.",
    objective: ["Improve campus security monitoring", "Detect unusual activity", "Provide real-time alerts", "Create a centralized monitoring interface"],
    requirements: ["Use IoT, sensors or smart monitoring technologies", "Provide useful security alerts", "Design an easy-to-use interface", "Demonstrate a practical campus use case"],
    deliverables: ["Working prototype", "Source code", "Project documentation", "Demo or presentation"],
    tags: ["IoT", "Safety", "Campus"],
  },
  {
    id: "SH-03",
    owner: "Student Experience Office",
    title: "AI Student Assistant",
    category: "Artificial Intelligence",
    difficulty: "Intermediate",
    points: 80,
    description: "Make schedules, resources and campus information easier to reach.",
    problem: "Students often need information from several sources. Build a centralized assistant that makes useful academic and campus information easier to access.",
    whyItMatters: "Less time searching means more time learning, collaborating and making progress.",
    objective: ["Create an intelligent student assistant", "Answer common student queries", "Provide useful academic information", "Improve student productivity"],
    requirements: ["Use AI or natural language processing", "Provide a conversational interface", "Handle common student queries", "Focus on accuracy and usability"],
    deliverables: ["Working prototype", "Source code", "Project documentation", "Demo or presentation"],
    tags: ["AI", "Education", "NLP"],
  },
  {
    id: "SH-04",
    owner: "Community Health Network",
    title: "Digital Health Innovation",
    category: "Healthcare",
    difficulty: "Advanced",
    points: 100,
    description: "Use technology to make healthcare more accessible, measurable and human.",
    problem: "Technology can improve healthcare accessibility and monitoring. Design a solution that addresses a practical healthcare challenge with care and clarity.",
    whyItMatters: "Better access and better signals can change outcomes for people who are often overlooked.",
    objective: ["Solve a real healthcare problem", "Improve accessibility or monitoring", "Use technology effectively", "Create a practical prototype"],
    requirements: ["Clearly define the healthcare problem", "Demonstrate the proposed solution", "Consider usability and reliability", "Explain the real-world impact"],
    deliverables: ["Working prototype", "Source code", "Project documentation", "Demo or presentation"],
    tags: ["Health", "Access", "Impact"],
  },
  {
    id: "SH-05",
    owner: "City Systems Collective",
    title: "Smart City Solution",
    category: "Smart City",
    difficulty: "Intermediate",
    points: 80,
    description: "Turn a city-scale problem into a practical, measurable intervention.",
    problem: "Growing cities face challenges in transportation, waste, energy and public services. Propose a scalable technology-based response to one of them.",
    whyItMatters: "Small improvements in public systems compound into healthier, more livable cities.",
    objective: ["Identify a real smart-city problem", "Design a technology-based solution", "Demonstrate measurable impact", "Create a scalable prototype"],
    requirements: ["Define a clear real-world problem", "Use suitable technologies", "Demonstrate the proposed workflow", "Explain scalability"],
    deliverables: ["Working prototype", "Source code", "Project documentation", "Demo or presentation"],
    tags: ["Civic", "Sustainability", "Systems"],
  },
  {
    id: "SH-06",
    owner: "Open Finance Forum",
    title: "Future FinTech Security",
    category: "FinTech",
    difficulty: "Advanced",
    points: 100,
    description: "Build trust into the next generation of financial technology.",
    problem: "Digital financial services face fraud and cyber threats. Create a solution that improves security, trust or fraud detection in financial technology.",
    whyItMatters: "Trust is the infrastructure that lets digital finance serve more people responsibly.",
    objective: ["Improve digital financial security", "Detect suspicious transactions or behaviour", "Protect user information", "Build a practical FinTech prototype"],
    requirements: ["Focus on security or fraud prevention", "Demonstrate the proposed workflow", "Consider privacy and usability", "Explain the potential real-world impact"],
    deliverables: ["Working prototype", "Source code", "Project documentation", "Demo or presentation"],
    tags: ["Finance", "Trust", "Privacy"],
  },
];

export const leaderboardPreview: LeaderboardEntry[] = [];
