"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import SiteHeader from "@/components/navigation/SiteHeader";
import { ButtonLink } from "@/components/ui/Button";
import { challenges } from "@/lib/constants";

export default function ProblemDetailsPage() {
  const params = useParams();
  const challenge = challenges.find((item) => item.id === String(params.id).toUpperCase());
  if (!challenge) return <main className="problem-page"><SiteHeader /><div className="not-found"><span>404 / NOT FOUND</span><h1>Problem not found.</h1><p>The challenge statement you are looking for does not exist.</p><Link href="/challenges" className="button button-black">Back to challenges <span>↗</span></Link></div></main>;
  return <main className="problem-page"><SiteHeader /><div className="problem-container"><header className="problem-header"><div><div className="problem-badges"><span className="mono">{challenge.id}</span><span>{challenge.category}</span><span>{challenge.difficulty}</span></div><p className="challenge-owner">PROBLEM OWNER / {challenge.owner}</p><h1>{challenge.title}</h1><p>{challenge.description}</p></div><div className="points-box"><span>CHALLENGE VALUE</span><strong>{challenge.points}</strong><small>POINTS</small></div></header><div className="problem-layout"><div className="problem-main"><section className="problem-card"><div className="problem-card-title"><span>01</span><h2>The problem</h2></div><p>{challenge.problem}</p></section><section className="problem-card"><div className="problem-card-title"><span>02</span><h2>Why it matters</h2></div><p>{challenge.whyItMatters}</p></section><section className="problem-card"><div className="problem-card-title"><span>03</span><h2>What you build</h2></div><div className="objective-list">{challenge.objective.map((item, index) => <div className="objective-item" key={item}><span>0{index + 1}</span><p>{item}</p></div>)}</div></section><section className="problem-card"><div className="problem-card-title"><span>04</span><h2>Constraints</h2></div><ul className="requirement-list">{challenge.requirements.map((item) => <li key={item}>{item}</li>)}</ul></section><section className="problem-card"><div className="problem-card-title"><span>05</span><h2>Deliverables</h2></div><div className="deliverable-grid">{challenge.deliverables.map((item, index) => <div className="deliverable-item" key={item}><span>0{index + 1}</span><p>{item}</p></div>)}</div></section></div><aside className="problem-sidebar"><div className="action-card"><span className="eyebrow">READY TO BUILD?</span><h3>Take the challenge.</h3><p>Register your participant account before forming your team and choosing your problem.</p><ButtonLink href="/register" variant="orange">Join Solution Hunt <span>↗</span></ButtonLink></div><div className="info-card"><span>CHALLENGE INFO</span><div><small>Problem owner</small><strong>{challenge.owner}</strong></div><div><small>Track</small><strong>{challenge.category}</strong></div><div><small>Difficulty</small><strong>{challenge.difficulty}</strong></div><div><small>Points</small><strong>{challenge.points}</strong></div></div><Link href="/challenges" className="back-challenges">← Explore all challenges</Link></aside></div></div><footer className="footer"><div className="container footer-inner"><span>Solution Hunt</span><p>Hunt the problem. Build the solution.</p></div></footer></main>;
}
